### ISSUE TITLE
How to setup the RPI and the Nextion

### ISSUE THREAD

**Issue by baszapf** [gregory-yet/Nextion#1]
@gregory-yet, thank you for this wrappers in Node.js and Python. 
Sorry to bother you, but to me it is not 100% clear how to hook up the Nextion to the RPI. Did you use a USB/Serial adapter or did you connect it to the GPIOs? Could you please shed some light on your hardware setup?

**Comment by gregory-yet** [comment]
Hello,

My Nextion screen is connected through GPIO of my RPi with a setup like that : http://raspberrypi.stackexchange.com/a/47851 so you should disable Terminal messages over serial connection, something like that.

Of course you can use Serial Adapter, it work 100% and no need to setup raspi-config. You should instead use something like "ttyUSBx".

GPIO serialport is ttyAMA0, and don't forget to download dependencies like "SerialPort" : npm install serialport@4.0.7 (if you have more recent version it may return hex character instead ascii but it's not really a problem, you can just convert)

After this setup you can use my client.js code.

If you have any question, tell me. Good luck :)
